### ISSUE TITLE
Individual Review 1 v 1

### ISSUE THREAD

**Issue by Emaad-Mir** [Emaad-Mir/emaad-github-pages1#7]
- [x] Blog showing your and  key assets and projects
  - [x] Show [research done on SQL databases](https://emaad-mir.github.io/emaad-github-pages1/c1.4/2023/12/13/Hashmaps-Hacks.html) 
  - [x] Tri 1 Projects/Work
    - [x] [Robot Socket Explanation](https://the-code-monkeys.github.io/Monkeys38//2023/11/02/RobotSocket.html)
    - [x] [2022 AP CSA FRQ #1 Explanation](https://emaad-mir.github.io/emaad-github-pages1/2023/09/12/FRQ-1-Methods-and-Control-Structures_IPYNB_2_.html) 
   - [x] Tri 2 Projects/Work
     - [x] [Mini Project (sorting race game)](https://github.com/TEE-CSA/TEE-Frontend/issues/8#issue-2036146171)
- [x] College Board prep and assets
  - [x] [College Board Corrections (prep resource) - 2015 MCQ ](https://emaad-mir.github.io/emaad-github-pages1/2023/12/21/MC-2015-Blog.html)
- [x] Blog timebox / Key Issues and other organization showing how you know where you have been and where you are going 
  - [x] [Timebox with all hacks/tangibles](https://emaad-mir.github.io/emaad-github-pages1/csa) 
- [x] GitHub commits for first half of the year
  - [x] Show live
- [x] Something you are passionate about in the upcoming project
  - [x] Something  I am passionate about in the upcoming project is AI and its versatility. For the next group project, we plan to create some sort of ASL application in which someone on camera can communicate a certain thing with sign language and the computer will be able to recognize it. We will be using some ASL data sets that we found online in order to accomplish this. 
- [x] Anything else you want to talk about
  - [x] Things I plan to carry over from my [mini project](https://github.com/TEE-CSA/TEE-Frontend/issues/8) to this project, mistakes I made in the mini project that I will not make in the new group project
  - [x] [Hangman game for fun ](https://emaad-mir.github.io/emaad-github-pages1/hangman)

![image](https://github.com/Emaad-Mir/emaad-github-pages1/assets/86995831/629a124c-8a6b-449f-b1ef-47b65fcabac1)
